# Generated by Django 5.2.6 on 2025-10-31 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_vendor'),
        ('vendor', '0005_alter_vendor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendor.vendor'),
            preserve_default=False,
        ),
    ]
