# Generated by Django 5.2.6 on 2025-11-05 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0003_alter_salesorder_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_payments', to='purchases.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_payments', to='sales.salesorder'),
        ),
    ]
