# Generated by Django 5.2.6 on 2025-11-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_purchase_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
    ]
