# Generated by Django 5.2.6 on 2025-11-19 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchaseorder_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
