# Generated by Django 5.2.6 on 2025-11-04 17:02

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorder_invoice_number_salesorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='invoice_number',
            field=models.CharField(default=sales.models.generate_invoice_number, max_length=50, unique=True),
        ),
    ]
