# Generated by Django 5.2.6 on 2025-11-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesorder_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='paid_amount',
            new_name='remaining_amount',
        ),
    ]
