# Generated by Django 5.2.6 on 2025-11-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesorder_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial_paid', 'Partial Paid'), ('full_paid', 'Full Paid')], default='unpaid', max_length=20),
        ),
    ]
