# Generated by Django 5.2.6 on 2025-11-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_salesorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial_paid', 'Partial-Paid'), ('full_paid', 'Full-Paid')], default='unpaid', max_length=20),
        ),
    ]
